#Values for the deployment
deployment:
  name: golang-app
  label: golang

#Image replicas
replicas: 1

#Container specs
container:
  image: szadhub/go-metrics
  pullPolicy: IfNotPresent
  tag: 7527715d0f6ec70d3c5dc408005092f4db09433f
  port: 5000

#Container resources
resources:
  requests:
    memory: "64Mi"
    cpu: "128m"
  limits:
    memory: "128Mi"
    cpu: "256m"

#Values for the service
service:
  name: go-metrics-svc
  serviceType: ClusterIP
  label: golang
  port: 80
  targetPort: 5000

#Values for horizontal pod autoscaling
hpa:
  enabled: true
  name: golang-app-hpa
  minReplicas: 1
  maxReplicas: 5
  avgCpuConsume: 70
  #avgMemConsume: 70

#Values for Traefik Ingress
ingress:
  enabled: true
  name: go-metrics-ingress
  annotations: {}
  routes:
    - match: '`blue.szanetwork.com`, `www.blue.szanetwork.com`'
      services:
        - name: nginx-deploy-blue
          port: 80
    - match: '`app.szanetwork.com`, `www.app.szanetwork.com`'
      services:
        - name: go-metrics-svc
          port: 80

#Bool for activate the nginx-blue deployment and service
#Just for study purposes and ensure the Traefik ingress is working properly
nginxblue:
  deployment: false
  service: false


