apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    argo: {{ .Values.deployment.label }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      argo: {{ .Values.deployment.label }}
  template:
    metadata:
      labels:
        argo: {{ .Values.deployment.label }}
    spec:
      containers:
        - name: {{ .Values.deployment.name }}
          image: "{{ .Values.container.image }}:{{ .Values.container.tag }}"
          imagePullPolicy: {{ .Values.container.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /
              port: 5000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.container.port }}
      