{{- if .Values.db.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.name }}
  labels:
    argo: {{ .Values.db.label }}
spec:
  selector:
    matchLabels:
      argo: {{ .Values.db.label }}
  template:
    metadata:
      labels:
        argo: {{ .Values.db.label }}
    spec:
      containers:
        - name: {{ .Values.db.name }}
          image: "{{ .Values.db.image }}:{{ .Values.db.dbver }}"
          imagePullPolicy: {{ .Values.db.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.db.port }}
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_DB
              value: "loja"
            - name: POSTGRES_PASSWORD
              value: "123"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}

spec:
  type: {{ .Values.db.serviceType }}  
  selector:
    argo: {{ .Values.db.label }}
  ports:
    - protocol: TCP
      port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
{{- end }}