apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}

spec:
  type: {{ .Values.service.serviceType }}  
  selector:
    argo: {{ .Values.service.label }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}